sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t kinggstark/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kinggstark/react-test npm test

after_success:
  - docker build -t kinggstark/multi-client ./client
  - docker build -t kinggstark/multi-nginx ./nginx
  - docker build -t kinggstark/multi-server ./server
  - docker build -t kinggstark/multi-worker ./worker
  #push to dockerhub
  - echo "$DOCKER_PASSWORD | docker login -u "$DOCKER_ID" --password-stdin
  - docker push -t kinggstark/multi-client
  - docker push -t kinggstark/multi-nginx
  - docker push -t kinggstark/multi-server
  - docker push -t kinggstark/multi-worker
